//! Validated self-play targets and a rolling, game-aware replay buffer.

use std::collections::VecDeque;

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::{
    Action, Game, HISTORY_POSITIONS, Outcome, POLICY_ACTIONS, Player, PolicyIndex, Position,
    Replay, ReplayError, SearchResult,
};

const POLICY_TOLERANCE: f32 = 1.0e-4;

/// Aggregate diagnostics derived only from self-play policy targets.
#[derive(Clone, Copy, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct PolicyTargetDiagnostics {
    /// Number of policy targets included in the aggregate.
    pub positions: usize,
    /// Mean Shannon entropy; higher values indicate less concentrated targets.
    pub mean_entropy: f32,
    /// Mean probability assigned to each target's most visited action.
    pub mean_max_probability: f32,
    /// Fraction of legal actions that received non-zero MCTS target mass.
    pub mean_legal_action_coverage: f32,
    /// Positions where at least one legal action would immediately draw.
    pub immediate_draw_positions: usize,
    /// Target mass assigned to immediate draws, averaged over those positions.
    pub mean_immediate_draw_mass: f32,
    /// Target mass assigned to actions reaching an already-seen position.
    pub mean_repetition_mass: f32,
}

/// Policy-target health split by final official outcome.
#[derive(Clone, Copy, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct DatasetDiagnostics {
    /// Aggregate over every recorded position.
    pub all: PolicyTargetDiagnostics,
    /// Aggregate restricted to games ending in an official draw.
    pub draws: PolicyTargetDiagnostics,
    /// Draw positions where the player to move also started the game.
    #[serde(default)]
    pub draw_starter: PolicyTargetDiagnostics,
    /// Draw positions where the player to move is expected to convert.
    #[serde(default)]
    pub draw_non_starter: PolicyTargetDiagnostics,
    /// Aggregate restricted to games with a winner.
    pub decisive: PolicyTargetDiagnostics,
}

/// One supervised `(position, MCTS policy, final outcome)` training sample.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrainingExample {
    /// Path-independent board state before the recorded action.
    pub position: Position,
    /// Occurrence count of this position along its full game path.
    pub repetition_count: u8,
    /// Whether the player to move also made the first move of the game.
    pub current_player_is_starter: bool,
    /// Resulting occurrence count for each legal policy action; zero elsewhere.
    #[serde(with = "action_repetition_serde")]
    pub action_repetition_counts: [u8; POLICY_ACTIONS],
    /// Runtime-only preceding states, reconstructed from the containing game.
    /// Keeping this out of JSON avoids duplicating history for every ply.
    #[serde(skip)]
    pub history: [Option<Position>; HISTORY_POSITIONS],
    #[serde(with = "policy_serde")]
    /// Normalized MCTS visit distribution over the fixed policy vector.
    pub policy: [f32; POLICY_ACTIONS],
    /// Final game result from `position.side_to_move()`'s perspective.
    pub value: f32,
}

/// Leaf evaluator that produced a persisted self-play trajectory.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum SelfPlayEvaluator {
    /// Learned policy and WDL network.
    #[default]
    Neural,
    /// Uniform-prior MCTS whose leaf value comes from random continuation.
    RandomRollout {
        /// Maximum actions played by each random leaf continuation.
        max_plies: usize,
    },
}

impl SelfPlayEvaluator {
    /// Reports whether this trajectory was generated by neural inference.
    #[must_use]
    pub const fn is_neural(&self) -> bool {
        matches!(self, Self::Neural)
    }

    /// Returns a stable short label for progress reports and filenames.
    #[must_use]
    pub const fn label(self) -> &'static str {
        match self {
            Self::Neural => "neural",
            Self::RandomRollout { .. } => "random_rollout",
        }
    }
}

impl TrainingExample {
    /// Reflects board, history and every action-indexed target consistently.
    #[must_use]
    pub fn mirrored(&self) -> Self {
        Self {
            position: self.position.mirrored_horizontally(),
            repetition_count: self.repetition_count,
            current_player_is_starter: self.current_player_is_starter,
            action_repetition_counts: mirror_action_values(
                &self.action_repetition_counts,
                self.position.side_to_move(),
            ),
            history: self
                .history
                .map(|position| position.map(Position::mirrored_horizontally)),
            policy: mirror_policy(&self.policy, self.position.side_to_move()),
            value: self.value,
        }
    }
}

/// Persisted experience and provenance for one complete self-play trajectory.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelfPlayGame {
    /// Candidate generation for which this game was generated.
    pub generation: u32,
    /// Deterministic per-game seed.
    pub seed: u64,
    /// Explicitly disambiguates bootstrap data from neural self-play.
    #[serde(default, skip_serializing_if = "SelfPlayEvaluator::is_neural")]
    pub evaluator: SelfPlayEvaluator,
    /// Official final result shared by every example's value target.
    pub outcome: Outcome,
    /// Number of historical prefix plies replayed before this trajectory began.
    #[serde(default, skip_serializing_if = "is_zero")]
    pub restart_ply: usize,
    /// Seven states immediately preceding the first recorded restart example.
    #[serde(default, skip_serializing_if = "history_is_empty")]
    pub restart_history: [Option<Position>; HISTORY_POSITIONS],
    /// Recorded suffix positions, excluding the terminal state.
    pub examples: Vec<TrainingExample>,
    /// Versioned game trace. Legacy buffers deserialize with no replay.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub replay: Option<Replay>,
}

impl SelfPlayGame {
    /// Returns owned examples, optionally interleaving every horizontal mirror.
    #[must_use]
    pub fn augmented_examples(&self, mirror: bool) -> Vec<TrainingExample> {
        self.selected_examples(mirror, None)
    }

    /// Reconstructs every non-initial, non-terminal state visited in this game.
    ///
    /// Multiple games may contribute the same state. Retaining those
    /// occurrences deliberately weights frequently visited regions when the
    /// restart archive is sampled uniformly.
    ///
    /// # Errors
    ///
    /// Returns [`ReplayError`] if the stored complete replay is invalid.
    pub fn visited_restart_replays(&self) -> Result<Vec<Replay>, ReplayError> {
        let Some(replay) = &self.replay else {
            return Ok(Vec::new());
        };
        replay.to_game()?;
        let mut prefixes = Vec::with_capacity(replay.actions.len().saturating_sub(1));
        for prefix_len in 1..replay.actions.len() {
            let prefix = Replay::from_actions(
                replay.initial_player,
                replay.actions[..prefix_len].to_vec(),
                Outcome::Ongoing,
                replay.seed,
            );
            prefix.to_game()?;
            prefixes.push(prefix);
        }
        Ok(prefixes)
    }

    /// Selects the complete game, or a tactical tail from a decisive game.
    ///
    /// A terminal window intentionally rejects draws: unlike a win, their last
    /// action is merely the action that repeated a position, not a forced tactic
    /// that the policy should learn to reproduce.
    #[must_use]
    pub fn selected_examples(
        &self,
        mirror: bool,
        terminal_window_plies: Option<usize>,
    ) -> Vec<TrainingExample> {
        let start = match terminal_window_plies {
            None => 0,
            Some(window) if matches!(self.outcome, Outcome::Win { .. }) => {
                self.examples.len().saturating_sub(window)
            }
            Some(_) => return Vec::new(),
        };
        let selected = (start..self.examples.len())
            .map(|index| self.example_with_history(index))
            .collect::<Vec<_>>();
        augment_examples(&selected, mirror)
    }

    fn example_with_history(&self, index: usize) -> TrainingExample {
        let mut example = self.examples[index].clone();
        example.history = std::array::from_fn(|offset| {
            index
                .checked_sub(offset + 1)
                .map(|previous| self.examples[previous].position)
                .or_else(|| {
                    offset
                        .checked_sub(index)
                        .and_then(|prefix_offset| self.restart_history[prefix_offset])
                })
        });
        example
    }
}

fn augment_examples(examples: &[TrainingExample], mirror: bool) -> Vec<TrainingExample> {
    if !mirror {
        return examples.to_vec();
    }
    let mut augmented = Vec::with_capacity(examples.len() * 2);
    for example in examples {
        augmented.push(example.clone());
        augmented.push(example.mirrored());
    }
    augmented
}

/// Builds policy targets online, then attaches final values after game end.
#[derive(Default)]
pub struct SelfPlayRecorder {
    pending: Vec<PendingExample>,
}

struct PendingExample {
    position: Position,
    repetition_count: u8,
    current_player_is_starter: bool,
    action_repetition_counts: [u8; POLICY_ACTIONS],
    policy: [f32; POLICY_ACTIONS],
    action: Action,
}

impl SelfPlayRecorder {
    /// Creates an empty trajectory recorder.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            pending: Vec::new(),
        }
    }

    /// Records a non-terminal state and its complete MCTS policy.
    ///
    /// # Errors
    ///
    /// Returns [`TrainingDataError`] for terminal states, invalid probability
    /// mass, or policy mass assigned to illegal actions.
    pub fn record(&mut self, game: &Game, search: &SearchResult) -> Result<(), TrainingDataError> {
        if game.outcome().is_terminal() {
            return Err(TrainingDataError::TerminalPolicyTarget);
        }
        validate_policy(game.position(), &search.policy)?;
        let player = game.position().side_to_move();
        let mut action_repetition_counts = [0; POLICY_ACTIONS];
        for action in game.legal_actions() {
            if let (Some(index), Some(count)) = (
                action.policy_index(player),
                game.repetition_count_after(action),
            ) {
                action_repetition_counts[index.as_usize()] = count;
            }
        }
        self.pending.push(PendingExample {
            position: *game.position(),
            repetition_count: game.current_repetition_count(),
            current_player_is_starter: player == game.initial_player(),
            action_repetition_counts,
            policy: search.policy,
            action: search.selected_action,
        });
        Ok(())
    }

    /// Assigns the final value to every recorded non-terminal state.
    ///
    /// # Errors
    ///
    /// Returns [`TrainingDataError`] when the supplied result is not terminal
    /// or no policy target was recorded.
    pub fn finish(
        self,
        generation: u32,
        seed: u64,
        outcome: Outcome,
    ) -> Result<SelfPlayGame, TrainingDataError> {
        if !outcome.is_terminal() {
            return Err(TrainingDataError::NonTerminalGame);
        }
        if self.pending.is_empty() {
            return Err(TrainingDataError::EmptyGame);
        }
        let initial_position = self
            .pending
            .first()
            .map(|pending| pending.position)
            .ok_or(TrainingDataError::EmptyGame)?;
        let initial_player = initial_position.side_to_move();
        let actions = self
            .pending
            .iter()
            .map(|pending| pending.action)
            .collect::<Vec<_>>();
        let replay = (initial_position == Position::initial(initial_player))
            .then(|| Replay::from_actions(initial_player, actions, outcome, Some(seed)));
        self.finish_with_replay(
            generation,
            seed,
            outcome,
            0,
            [None; HISTORY_POSITIONS],
            replay,
        )
    }

    /// Finishes a trajectory that may have started from a replayed game prefix.
    ///
    /// # Errors
    ///
    /// Returns [`TrainingDataError`] if the final game is not terminal or its
    /// suffix does not match the recorded policy targets.
    pub fn finish_from_game(
        self,
        generation: u32,
        seed: u64,
        game: &Game,
        restart_ply: usize,
    ) -> Result<SelfPlayGame, TrainingDataError> {
        if !game.outcome().is_terminal() {
            return Err(TrainingDataError::NonTerminalGame);
        }
        let suffix = game
            .actions()
            .get(restart_ply..)
            .ok_or(TrainingDataError::InvalidRestartTrace)?;
        if suffix.len() != self.pending.len()
            || suffix
                .iter()
                .zip(&self.pending)
                .any(|(action, pending)| *action != pending.action)
        {
            return Err(TrainingDataError::InvalidRestartTrace);
        }
        let positions = game.position_history();
        let restart_history = std::array::from_fn(|offset| {
            restart_ply
                .checked_sub(offset + 1)
                .map(|index| positions[index])
        });
        self.finish_with_replay(
            generation,
            seed,
            game.outcome(),
            restart_ply,
            restart_history,
            Some(Replay::from_game(game, Some(seed))),
        )
    }

    fn finish_with_replay(
        self,
        generation: u32,
        seed: u64,
        outcome: Outcome,
        restart_ply: usize,
        restart_history: [Option<Position>; HISTORY_POSITIONS],
        replay: Option<Replay>,
    ) -> Result<SelfPlayGame, TrainingDataError> {
        if self.pending.is_empty() {
            return Err(TrainingDataError::EmptyGame);
        }
        let examples = self
            .pending
            .into_iter()
            .map(|pending| TrainingExample {
                position: pending.position,
                repetition_count: pending.repetition_count,
                current_player_is_starter: pending.current_player_is_starter,
                action_repetition_counts: pending.action_repetition_counts,
                history: [None; HISTORY_POSITIONS],
                policy: pending.policy,
                value: outcome_value(outcome, pending.position.side_to_move()),
            })
            .collect();
        Ok(SelfPlayGame {
            generation,
            seed,
            evaluator: SelfPlayEvaluator::Neural,
            outcome,
            restart_ply,
            restart_history,
            examples,
            replay,
        })
    }
}

/// Age and capacity limits of the rolling game buffer.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct ReplayBufferConfig {
    /// Hard maximum number of complete games retained.
    pub max_games: usize,
    /// Maximum age relative to the newest pushed generation.
    pub generations_to_keep: u32,
}

impl Default for ReplayBufferConfig {
    fn default() -> Self {
        Self {
            max_games: 20_000,
            generations_to_keep: 20,
        }
    }
}

/// Game-aware rolling experience store used for training and validation.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ReplayBuffer {
    config: ReplayBufferConfig,
    games: VecDeque<SelfPlayGame>,
}

impl ReplayBuffer {
    /// Creates a rolling replay buffer.
    ///
    /// # Errors
    ///
    /// Returns [`TrainingDataError`] when either retention limit is zero.
    pub fn new(config: ReplayBufferConfig) -> Result<Self, TrainingDataError> {
        if config.max_games == 0 || config.generations_to_keep == 0 {
            return Err(TrainingDataError::InvalidBufferConfiguration);
        }
        Ok(Self {
            config,
            games: VecDeque::new(),
        })
    }

    /// Adds a game, then evicts entries outside age and capacity limits.
    pub fn push(&mut self, game: SelfPlayGame) {
        let oldest_generation = game
            .generation
            .saturating_add(1)
            .saturating_sub(self.config.generations_to_keep);
        self.games
            .retain(|stored| stored.generation >= oldest_generation);
        self.games.push_back(game);
        while self.games.len() > self.config.max_games {
            self.games.pop_front();
        }
    }

    /// Returns the number of retained complete games.
    #[must_use]
    pub fn len(&self) -> usize {
        self.games.len()
    }

    /// Reports whether the buffer contains no games.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.games.is_empty()
    }

    /// Checks whether one generation/seed identity is already retained.
    #[must_use]
    pub fn contains(&self, generation: u32, seed: u64) -> bool {
        self.games
            .iter()
            .any(|game| game.generation == generation && game.seed == seed)
    }

    /// Returns the number of recorded nonterminal positions before augmentation.
    #[must_use]
    pub fn example_count(&self) -> usize {
        self.games.iter().map(|game| game.examples.len()).sum()
    }

    /// Returns every validated non-initial, non-terminal visited prefix.
    ///
    /// # Errors
    ///
    /// Returns [`ReplayError`] if a stored full-game replay is invalid.
    pub fn visited_restart_replays(&self) -> Result<Vec<Replay>, ReplayError> {
        let mut replays = Vec::new();
        for game in &self.games {
            replays.extend(game.visited_restart_replays()?);
        }
        Ok(replays)
    }

    /// Computes policy-target health aggregates over the current buffer.
    #[must_use]
    pub fn diagnostics(&self) -> DatasetDiagnostics {
        dataset_diagnostics(&self.games)
    }

    /// Splits whole games so positions from one game cannot leak across train
    /// and validation sets.
    ///
    /// # Errors
    ///
    /// Returns [`TrainingDataError`] for a non-finite fraction outside `[0, 1]`.
    pub fn split(
        &self,
        validation_fraction: f32,
        seed: u64,
    ) -> Result<DatasetSplit, TrainingDataError> {
        if !validation_fraction.is_finite() || !(0.0..=1.0).contains(&validation_fraction) {
            return Err(TrainingDataError::InvalidValidationFraction);
        }
        let mut training_games = Vec::new();
        let mut validation_games = Vec::new();
        for game in &self.games {
            if belongs_to_validation(game, validation_fraction, seed) {
                validation_games.push(game.clone());
            } else {
                training_games.push(game.clone());
            }
        }
        // Hash bucketing is stable as the buffer grows. These fallbacks matter
        // only for tiny test/bootstrap corpora where a bucket can be empty.
        if training_games.is_empty() && !validation_games.is_empty() {
            if let Some(game) = validation_games.pop() {
                training_games.push(game);
            }
        } else if validation_fraction > 0.0
            && validation_games.is_empty()
            && training_games.len() > 1
            && let Some(game) = training_games.pop()
        {
            validation_games.push(game);
        }
        Ok(DatasetSplit {
            training_games,
            validation_games,
        })
    }
}

/// Computes outcome- and role-split diagnostics from policy targets alone.
#[must_use]
pub fn dataset_diagnostics<'a>(
    games: impl IntoIterator<Item = &'a SelfPlayGame>,
) -> DatasetDiagnostics {
    let mut all = PolicyTargetAccumulator::default();
    let mut draws = PolicyTargetAccumulator::default();
    let mut draw_starter = PolicyTargetAccumulator::default();
    let mut draw_non_starter = PolicyTargetAccumulator::default();
    let mut decisive = PolicyTargetAccumulator::default();
    for game in games {
        let is_draw = matches!(game.outcome, Outcome::Draw { .. });
        for example in &game.examples {
            all.add(example);
            if is_draw {
                draws.add(example);
                if example.current_player_is_starter {
                    draw_starter.add(example);
                } else {
                    draw_non_starter.add(example);
                }
            } else {
                decisive.add(example);
            }
        }
    }
    DatasetDiagnostics {
        all: all.finish(),
        draws: draws.finish(),
        draw_starter: draw_starter.finish(),
        draw_non_starter: draw_non_starter.finish(),
        decisive: decisive.finish(),
    }
}

#[derive(Default)]
struct PolicyTargetAccumulator {
    positions: usize,
    entropy: f32,
    max_probability: f32,
    legal_action_coverage: f32,
    immediate_draw_positions: usize,
    immediate_draw_mass: f32,
    repetition_mass: f32,
}

impl PolicyTargetAccumulator {
    fn add(&mut self, example: &TrainingExample) {
        self.positions += 1;
        self.entropy += example
            .policy
            .iter()
            .filter(|probability| **probability > 0.0)
            .map(|probability| -probability * probability.ln())
            .sum::<f32>();
        self.max_probability += example.policy.iter().copied().fold(0.0_f32, f32::max);

        let player = example.position.side_to_move();
        let legal = example.position.legal_actions();
        let visited = legal
            .iter()
            .filter_map(|action| action.policy_index(player))
            .filter(|index| example.policy[index.as_usize()] > 0.0)
            .count();
        self.legal_action_coverage += ratio(visited, legal.len());

        let immediate_draw_mass = example
            .policy
            .iter()
            .zip(example.action_repetition_counts)
            .filter(|(_, count)| *count >= 3)
            .map(|(probability, _)| probability)
            .sum::<f32>();
        if example
            .action_repetition_counts
            .iter()
            .any(|count| *count >= 3)
        {
            self.immediate_draw_positions += 1;
            self.immediate_draw_mass += immediate_draw_mass;
        }
        self.repetition_mass += example
            .policy
            .iter()
            .zip(example.action_repetition_counts)
            .filter(|(_, count)| *count >= 2)
            .map(|(probability, _)| probability)
            .sum::<f32>();
    }

    fn finish(self) -> PolicyTargetDiagnostics {
        let positions = self.positions.max(1);
        PolicyTargetDiagnostics {
            positions: self.positions,
            mean_entropy: self.entropy / count_as_f32(positions),
            mean_max_probability: self.max_probability / count_as_f32(positions),
            mean_legal_action_coverage: self.legal_action_coverage / count_as_f32(positions),
            immediate_draw_positions: self.immediate_draw_positions,
            mean_immediate_draw_mass: self.immediate_draw_mass
                / count_as_f32(self.immediate_draw_positions.max(1)),
            mean_repetition_mass: self.repetition_mass / count_as_f32(positions),
        }
    }
}

#[allow(clippy::cast_precision_loss)]
fn ratio(numerator: usize, denominator: usize) -> f32 {
    numerator as f32 / denominator.max(1) as f32
}

#[allow(clippy::cast_precision_loss)]
fn count_as_f32(count: usize) -> f32 {
    count as f32
}

/// Stable whole-game partition used by optimization and diagnostics.
#[derive(Clone, Debug)]
pub struct DatasetSplit {
    /// Games eligible for gradient updates.
    pub training_games: Vec<SelfPlayGame>,
    /// Games reserved exclusively for evaluation metrics.
    pub validation_games: Vec<SelfPlayGame>,
}

impl DatasetSplit {
    /// Collects full training games with optional horizontal augmentation.
    #[must_use]
    pub fn training_examples(&self, mirror: bool) -> Vec<TrainingExample> {
        self.training_examples_with_window(mirror, None)
    }

    /// Collects training samples under an optional decisive-tail filter.
    #[must_use]
    pub fn training_examples_with_window(
        &self,
        mirror: bool,
        terminal_window_plies: Option<usize>,
    ) -> Vec<TrainingExample> {
        self.training_games
            .iter()
            .flat_map(|game| game.selected_examples(mirror, terminal_window_plies))
            .collect()
    }

    /// Collects unaugmented examples from every validation game.
    #[must_use]
    pub fn validation_examples(&self) -> Vec<TrainingExample> {
        self.validation_examples_with_window(None)
    }

    /// Collects validation samples under the same optional decisive-tail filter.
    #[must_use]
    pub fn validation_examples_with_window(
        &self,
        terminal_window_plies: Option<usize>,
    ) -> Vec<TrainingExample> {
        self.validation_games
            .iter()
            .flat_map(|game| game.selected_examples(false, terminal_window_plies))
            .collect()
    }

    /// Counts games contributing samples after applying the window rule.
    #[must_use]
    pub fn selected_game_counts(&self, terminal_window_plies: Option<usize>) -> (usize, usize) {
        let is_selected = |game: &&SelfPlayGame| {
            terminal_window_plies.is_none() || matches!(game.outcome, Outcome::Win { .. })
        };
        (
            self.training_games.iter().filter(is_selected).count(),
            self.validation_games.iter().filter(is_selected).count(),
        )
    }
}

/// Invalid self-play targets, trajectory finalization or dataset settings.
#[derive(Clone, Debug, Error, PartialEq)]
pub enum TrainingDataError {
    /// A policy target was recorded after game end.
    #[error("terminal states cannot have policy targets")]
    TerminalPolicyTarget,
    /// Recorder finalization received an ongoing outcome.
    #[error("self-play result must be terminal")]
    NonTerminalGame,
    /// Recorded actions differ from the supplied restarted-game suffix.
    #[error("recorded self-play actions do not match the restarted game suffix")]
    InvalidRestartTrace,
    /// A finished trajectory contains no supervised positions.
    #[error("a self-play game cannot contain zero training states")]
    EmptyGame,
    /// Policy contains NaN, infinity or a negative probability.
    #[error("policy contains a non-finite or negative probability")]
    InvalidPolicyValue,
    /// Policy probabilities do not sum approximately to one.
    #[error("policy probability mass must sum to one, got {0}")]
    InvalidPolicyMass(f32),
    /// Policy assigns meaningful mass to actions illegal in the position.
    #[error("policy assigns {0} probability mass to illegal actions")]
    IllegalPolicyMass(f32),
    /// Replay-buffer age or capacity was configured as zero.
    #[error("replay buffer retention limits must be positive")]
    InvalidBufferConfiguration,
    /// Validation fraction is non-finite or outside `[0, 1]`.
    #[error("validation fraction must be finite and between zero and one")]
    InvalidValidationFraction,
}

#[allow(clippy::trivially_copy_pass_by_ref)]
const fn is_zero(value: &usize) -> bool {
    *value == 0
}

fn history_is_empty(history: &[Option<Position>; HISTORY_POSITIONS]) -> bool {
    history.iter().all(Option::is_none)
}

/// Mirrors a canonical policy horizontally while preserving invalid slots.
#[must_use]
pub fn mirror_policy(policy: &[f32; POLICY_ACTIONS], player: Player) -> [f32; POLICY_ACTIONS] {
    let mut mirrored = [0.0; POLICY_ACTIONS];
    for (raw_index, &probability) in policy.iter().enumerate() {
        let Ok(raw_index_u8) = u8::try_from(raw_index) else {
            continue;
        };
        let Some(index) = PolicyIndex::new(raw_index_u8) else {
            continue;
        };
        let Some(action) = Action::from_policy_index(index, player) else {
            continue;
        };
        let Some(mirrored_index) = action.mirrored_horizontally().policy_index(player) else {
            continue;
        };
        mirrored[mirrored_index.as_usize()] = probability;
    }
    mirrored
}

fn mirror_action_values<T: Copy + Default>(
    values: &[T; POLICY_ACTIONS],
    player: Player,
) -> [T; POLICY_ACTIONS] {
    let mut mirrored = [T::default(); POLICY_ACTIONS];
    for (raw_index, &value) in values.iter().enumerate() {
        let Ok(raw_index_u8) = u8::try_from(raw_index) else {
            continue;
        };
        let Some(index) = PolicyIndex::new(raw_index_u8) else {
            continue;
        };
        let Some(action) = Action::from_policy_index(index, player) else {
            continue;
        };
        let Some(mirrored_index) = action.mirrored_horizontally().policy_index(player) else {
            continue;
        };
        mirrored[mirrored_index.as_usize()] = value;
    }
    mirrored
}

#[allow(
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_sign_loss
)]
fn validation_game_count(game_count: usize, fraction: f32) -> usize {
    ((game_count as f32) * fraction).round() as usize
}

fn belongs_to_validation(game: &SelfPlayGame, fraction: f32, seed: u64) -> bool {
    const BUCKETS: usize = 10_000;
    let threshold = validation_game_count(BUCKETS, fraction);
    if threshold == 0 {
        return false;
    }
    let identity = seed
        ^ game.seed.rotate_left(17)
        ^ u64::from(game.generation).wrapping_mul(0x9e37_79b9_7f4a_7c15);
    splitmix64(identity) % (BUCKETS as u64) < threshold as u64
}

const fn splitmix64(mut value: u64) -> u64 {
    value = value.wrapping_add(0x9e37_79b9_7f4a_7c15);
    value = (value ^ (value >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
    value = (value ^ (value >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
    value ^ (value >> 31)
}

fn validate_policy(
    position: &Position,
    policy: &[f32; POLICY_ACTIONS],
) -> Result<(), TrainingDataError> {
    if policy
        .iter()
        .any(|probability| !probability.is_finite() || *probability < 0.0)
    {
        return Err(TrainingDataError::InvalidPolicyValue);
    }
    let total = policy.iter().sum::<f32>();
    if (total - 1.0).abs() > POLICY_TOLERANCE {
        return Err(TrainingDataError::InvalidPolicyMass(total));
    }
    let game = Game::from_position(*position);
    let legal_mass = game
        .legal_actions()
        .into_iter()
        .filter_map(|action| action.policy_index(position.side_to_move()))
        .map(|index| policy[index.as_usize()])
        .sum::<f32>();
    let illegal_mass = (total - legal_mass).max(0.0);
    if illegal_mass > POLICY_TOLERANCE {
        return Err(TrainingDataError::IllegalPolicyMass(illegal_mass));
    }
    Ok(())
}

fn outcome_value(outcome: Outcome, perspective: Player) -> f32 {
    match outcome {
        Outcome::Ongoing | Outcome::Draw { .. } => 0.0,
        Outcome::Win { player, .. } if player == perspective => 1.0,
        Outcome::Win { .. } => -1.0,
    }
}

mod policy_serde {
    use serde::{Deserialize, Deserializer, Serialize, Serializer, de::Error as _};

    use crate::POLICY_ACTIONS;

    pub fn serialize<S>(policy: &[f32; POLICY_ACTIONS], serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        policy.as_slice().serialize(serializer)
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<[f32; POLICY_ACTIONS], D::Error>
    where
        D: Deserializer<'de>,
    {
        Vec::<f32>::deserialize(deserializer)?
            .try_into()
            .map_err(|values: Vec<f32>| {
                D::Error::custom(format_args!(
                    "expected {POLICY_ACTIONS} policy values, got {}",
                    values.len()
                ))
            })
    }
}

mod action_repetition_serde {
    use serde::{Deserialize, Deserializer, Serialize, Serializer, de::Error as _};

    use crate::POLICY_ACTIONS;

    pub fn serialize<S>(counts: &[u8; POLICY_ACTIONS], serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        counts.as_slice().serialize(serializer)
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<[u8; POLICY_ACTIONS], D::Error>
    where
        D: Deserializer<'de>,
    {
        Vec::<u8>::deserialize(deserializer)?
            .try_into()
            .map_err(|values: Vec<u8>| {
                D::Error::custom(format_args!(
                    "expected {POLICY_ACTIONS} action repetition counts, got {}",
                    values.len()
                ))
            })
    }
}
